const rankingData = [
  {
    rank: 1,
    title: '달콤한 허니 버터 갈릭 쉬림프',
    desc: '달콤 짭짤, 톡톡 터지는 새우의 맛',
    img: '11_shrimp.jpg',
    rating: 4.8,
    views: 120450,
    link: '11_인공띠용지능_detail_r1.html',
  },
  {
    rank: 2,
    title: '5분 완성! 초간단 샐러드 파스타',
    desc: '5분 만에 뚝딱! 가볍고 신선한 맛',
    img: '11_saladpasta.jpg',
    rating: 4.9,
    views: 98760,
    link: '11_인공띠용지능_detail_r2.html',
  },
  {
    rank: 3,
    title: '단짠단짠 마약 옥수수',
    desc: '멈출 수 없는 단짠 조합',
    img: '11_corn.jpg',
    rating: 4.3,
    views: 72110,
    link: '11_인공띠용지능_detail_r3.html',
  },
  {
    rank: 4,
    title: '고급진 부채살 스테이크',
    desc: '육즙 가득! 집에서 즐기는 만찬',
    img: '11_steak.jpg',
    rating: 4.5,
    views: 55900,
    link: '11_인공띠용지능_detail_r4.html',
  },
  {
    rank: 5,
    title: '상큼 시원 자몽 에이드',
    desc: '카페 퀄리티의 청량함',
    img: '11_drink.png',
    rating: 4.7,
    views: 48200,
    link: '11_인공띠용지능_detail_dr.html',
  },
];
