const recipeData = {
  korean: [
    {
      title: '김치찌개',
      img: '11_kimchi.jpg',
      author: '집밥여왕',
      views: '10.5K',
      rating: '★★★★☆ (4.8)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '비빔밥',
      img: '11_kimchi.jpg',
      author: '건강식단',
      views: '8.2K',
      rating: '★★★★☆ (4.4)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '불고기',
      img: '11_kimchi.jpg',
      author: '요리연습',
      views: '15.1K',
      rating: '★★★★★ (4.9)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '잡채',
      img: '11_kimchi.jpg',
      author: '한식연구소',
      views: '6.3K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '떡볶이',
      img: '11_kimchi.jpg',
      author: '분식천재',
      views: '21.4K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '순두부찌개',
      img: '11_kimchi.jpg',
      author: '따끈국물',
      views: '5.7K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '된장찌개',
      img: '11_kimchi.jpg',
      author: '시골밥상',
      views: '12.1K',
      rating: '★★★★☆ (4.4)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '김밥',
      img: '11_kimchi.jpg',
      author: '도시락장인',
      views: '9.3K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '감자탕',
      img: '11_kimchi.jpg',
      author: '국물요정',
      views: '4.8K',
      rating: '★★★★☆ (4.1)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '삼겹살',
      img: '11_kimchi.jpg',
      author: '고기장인',
      views: '18.9K',
      rating: '★★★★★ (4.9)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '갈비찜',
      img: '11_kimchi.jpg',
      author: '명절요리',
      views: '7.7K',
      rating: '★★★★★ (4.8)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '해물파전',
      img: '11_kimchi.jpg',
      author: '전굽는날',
      views: '6.0K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '냉면',
      img: '11_kimchi.jpg',
      author: '시원한집',
      views: '11.2K',
      rating: '★★★★☆ (4.4)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '김치볶음밥',
      img: '11_kimchi.jpg',
      author: '한그릇',
      views: '22.0K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_k.html',
    },
    {
      title: '닭갈비',
      img: '11_kimchi.jpg',
      author: '춘천맛집',
      views: '9.9K',
      rating: '★★★★☆ (4.6)',
      link: '11_인공띠용지능_detail_k.html',
    },
  ],

  chinese: [
    {
      title: '마라탕',
      img: '11_chinese.png',
      author: '얼얼이',
      views: '78.5K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '마파두부',
      img: '11_chinese.png',
      author: '사천요리',
      views: '9.1K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '탕수육',
      img: '11_chinese.png',
      author: '중식의달인',
      views: '20.3K',
      rating: '★★★★☆ (4.6)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '차우면',
      img: '11_chinese.png',
      author: '면요리연구소',
      views: '6.2K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '탄탄면',
      img: '11_chinese.png',
      author: '사천미식',
      views: '5.9K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '산라탕',
      img: '11_chinese.png',
      author: '국물장인',
      views: '4.0K',
      rating: '★★★★☆ (4.1)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '샤오룽바오',
      img: '11_chinese.png',
      author: '상하이키친',
      views: '7.8K',
      rating: '★★★★★ (4.7)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '베이징덕',
      img: '11_chinese.png',
      author: '북경요리',
      views: '3.6K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '어향가지',
      img: '11_chinese.png',
      author: '가지요리',
      views: '5.3K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '마라샹궈',
      img: '11_chinese.png',
      author: '마라의정석',
      views: '10.2K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_c.html',
    },
    {
      title: '계란볶음밥',
      img: '11_chinese.png',
      author: '간단중식',
      views: '12.5K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_c.html',
    },
  ],

  western: [
    {
      title: '정통 까르보나라',
      img: '11_pasta.jpg',
      author: '파스타장인',
      views: '12.3K',
      rating: '★★★★★ (4.9)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '갈릭 쉬림프 파스타',
      img: '11_pasta.jpg',
      author: '쉬운요리',
      views: '9.8K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '마르게리타 피자',
      img: '11_pasta.jpg',
      author: '화덕의정석',
      views: '14.0K',
      rating: '★★★★★ (4.8)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '볼로네제 파스타',
      img: '11_pasta.jpg',
      author: '미트소스러버',
      views: '8.7K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '알프레도 크림파스타',
      img: '11_pasta.jpg',
      author: '크리미',
      views: '7.1K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '스테이크',
      img: '11_pasta.jpg',
      author: '미디움레어',
      views: '16.2K',
      rating: '★★★★★ (4.8)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '라자냐',
      img: '11_pasta.jpg',
      author: '오븐요리',
      views: '6.5K',
      rating: '★★★★☆ (4.4)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '버섯 리조또',
      img: '11_pasta.jpg',
      author: '이탈리안홈',
      views: '5.4K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '그릭 샐러드',
      img: '11_pasta.jpg',
      author: '샐러디스트',
      views: '7.9K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '피시앤칩스',
      img: '11_pasta.jpg',
      author: '브리티시홈',
      views: '4.4K',
      rating: '★★★★☆ (4.1)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '수제 버거',
      img: '11_pasta.jpg',
      author: '그릴마스터',
      views: '13.0K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '클램 차우더',
      img: '11_pasta.jpg',
      author: '보스턴가정식',
      views: '3.8K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '펜네 아라비아따',
      img: '11_pasta.jpg',
      author: '매콤한파스타',
      views: '7.4K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '치킨 파르미지아나',
      img: '11_pasta.jpg',
      author: '오븐마스터',
      views: '10.1K',
      rating: '★★★★★ (4.7)',
      link: '11_인공띠용지능_detail_w.html',
    },
    {
      title: '쉬림프 스캄피',
      img: '11_pasta.jpg',
      author: '씨푸드러버',
      views: '8.6K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_w.html',
    },
  ],

  dessert: [
    {
      title: '아몬드 쿠키',
      img: '11_snack.jpg',
      author: '베이킹홀릭',
      views: '58.1K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '블론디',
      img: '11_snack.jpg',
      author: '베이킹러버',
      views: '5.2K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '초코 브라우니',
      img: '11_snack.jpg',
      author: '초코중독',
      views: '18.2K',
      rating: '★★★★★ (4.8)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '치즈케이크',
      img: '11_snack.jpg',
      author: '뉴욕베이커리',
      views: '9.0K',
      rating: '★★★★★ (4.7)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '티라미수',
      img: '11_snack.jpg',
      author: '디저트소믈리에',
      views: '7.6K',
      rating: '★★★★☆ (4.6)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '마카롱',
      img: '11_snack.jpg',
      author: '프렌치디저트',
      views: '12.7K',
      rating: '★★★★☆ (4.4)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '애플파이',
      img: '11_snack.jpg',
      author: '홈베이킹',
      views: '6.9K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '레몬 타르트',
      img: '11_snack.jpg',
      author: '시트러스러버',
      views: '4.3K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '판나코타',
      img: '11_snack.jpg',
      author: '이탈리안디저트',
      views: '3.5K',
      rating: '★★★★☆ (4.1)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '크림 브륄레',
      img: '11_snack.jpg',
      author: '파리지앵',
      views: '5.1K',
      rating: '★★★★★ (4.7)',
      link: '11_인공띠용지능_detail_d.html',
    },
    {
      title: '초코칩 쿠키',
      img: '11_snack.jpg',
      author: '쿠키하우스',
      views: '19.8K',
      rating: '★★★★★ (4.8)',
      link: '11_인공띠용지능_detail_d.html',
    },
  ],

  drink: [
    {
      title: '자몽 에이드',
      img: '11_drink.png',
      author: '홈카페달인',
      views: '52.4K',
      rating: '★★★★★ (4.7)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '딸기 에이드',
      img: '11_drink.png',
      author: '홈카페',
      views: '3.9K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '아이스 아메리카노',
      img: '11_drink.png',
      author: '카페인러버',
      views: '22.4K',
      rating: '★★★★☆ (4.6)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '라떼',
      img: '11_drink.png',
      author: '라떼아트',
      views: '9.1K',
      rating: '★★★★★ (4.7)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '카푸치노',
      img: '11_drink.png',
      author: '홈바리스타',
      views: '6.2K',
      rating: '★★★★☆ (4.4)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '레모네이드',
      img: '11_drink.png',
      author: '상큼상큼',
      views: '8.0K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '망고 스무디',
      img: '11_drink.png',
      author: '스무디왕',
      views: '12.1K',
      rating: '★★★★★ (4.7)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '초코 밀크셰이크',
      img: '11_drink.png',
      author: '달달카페',
      views: '10.3K',
      rating: '★★★★☆ (4.5)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '버블티',
      img: '11_drink.png',
      author: '타피오카',
      views: '18.8K',
      rating: '★★★★☆ (4.6)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '논알콜 모히또',
      img: '11_drink.png',
      author: '민트사랑',
      views: '4.6K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '핫초코',
      img: '11_drink.png',
      author: '겨울간식',
      views: '7.2K',
      rating: '★★★★☆ (4.3)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '복숭아 아이스티',
      img: '11_drink.png',
      author: '티메이커',
      views: '6.8K',
      rating: '★★★★☆ (4.2)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '히비스커스 티',
      img: '11_drink.png',
      author: '허브티',
      views: '6.6K',
      rating: '★★★★☆ (4.4)',
      link: '11_인공띠용지능_detail_dr.html',
    },
    {
      title: '바닐라 라떼',
      img: '11_drink.png',
      author: '라떼아트',
      views: '13.9K',
      rating: '★★★★★ (4.8)',
      link: '11_인공띠용지능_detail_dr.html',
    },
  ],
};
